---
collections:
  - name: community.aws
  - name: amazon.aws
  - name: ansible.controller
  #- name: community.general
  - name: ansible-controller
    src: https://github.com/amarmh/branch-testing/blob/main/ansible-controller-latest.tar.gz
    version: main
